// Static HTML renderers for the Dragon Oak storefront. Pure functions: (public catalog) -> strings.
//
// SECURITY: renderers only ever receive the PUBLIC catalog projection (api/_lib/catalog.js buildPublicCatalog), so
// digital-file references, internal notes and Etsy internals cannot appear in any page. Every dynamic value is HTML-escaped.
const { PRODUCT_TYPE_LABELS } = require("../api/_lib/catalog");

const SITE_ORIGIN = "https://dragonoakstudio.com";
const SITE_NAME = "Dragon Oak Studio";
const DEFAULT_SOCIAL_IMAGE = "/assets/dragon-oak-social-share.jpg";
const GENERATED_NOTE = "Generated by tools/build-storefront.js from catalog/. Do not edit by hand; run npm run catalog:build.";

const HOME_MARKERS = {
  start: "<!-- storefront:collections:start (generated by tools/build-storefront.js; do not edit between the markers) -->",
  end: "<!-- storefront:collections:end -->",
};

const escapeHtml = (value) =>
  String(value === undefined || value === null ? "" : value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

// JSON for <script type="application/ld+json">: neutralise anything that could close the script element early.
const safeJsonLd = (value) =>
  JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .split(String.fromCharCode(0x2028))
    .join("\\u2028")
    .split(String.fromCharCode(0x2029))
    .join("\\u2029");

const absoluteUrl = (pathOrUrl) => (/^https?:\/\//i.test(pathOrUrl) ? pathOrUrl : `${SITE_ORIGIN}${pathOrUrl}`);
const assetUrl = (relativePath) => `/${relativePath}`;
const imageUrl = (pathOrUrl) => (/^https?:\/\//i.test(pathOrUrl) ? pathOrUrl : assetUrl(pathOrUrl));
const pluralPieces = (count) => (count === 1 ? "1 piece" : `${count} pieces`);

const paragraphs = (text) =>
  String(text || "")
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean)
    .map((block) => `<p>${escapeHtml(block).replace(/\n/g, "<br />")}</p>`)
    .join("\n            ");

const headerHtml = ({ activeNav }) => `  <header class="site-header">
    <div class="container nav">
      <a class="brand" href="/" aria-label="Dragon Oak Studio home">
        <span class="mini-crest" aria-hidden="true">◆</span>
        <span class="brand-name">
          DRAGON OAK
          <small>STUDIO</small>
        </span>
      </a>

      <nav class="site-nav" aria-label="Main navigation">
        <button
          class="menu-toggle"
          id="menuToggle"
          type="button"
          aria-controls="navMenu"
          aria-expanded="false"
          aria-label="Open menu"
        >
          ☰
        </button>

        <ul id="navMenu" class="nav-menu">
          <li><a href="/#home">HOME</a></li>
          <li><a href="/#about">ABOUT</a></li>
          <li><a href="/shop/"${activeNav === "shop" ? ' aria-current="page"' : ""}>SHOP</a></li>
          <li><a href="/#custom">CUSTOM WORK</a></li>
          <li><a href="/#contact">CONTACT</a></li>
        </ul>
      </nav>
    </div>
  </header>`;

const footerHtml = () => `  <footer class="site-footer">
    <div class="container">
      <div class="footer-grid">
        <div>
          <a class="brand" href="/" aria-label="Dragon Oak Studio home">
            <span class="mini-crest" aria-hidden="true">◆</span>
            <span class="brand-name">
              DRAGON OAK
              <small>STUDIO</small>
            </span>
          </a>

          <p class="footer-tagline">Crafted by Fire. Designed to Last.</p>
        </div>

        <div>
          <h4>Quick Links</h4>
          <div class="footer-links">
            <a href="/#home">Home</a>
            <a href="/#about">About</a>
            <a href="/shop/">Shop</a>
            <a href="/#custom">Custom Work</a>
            <a href="/#contact">Contact</a>
          </div>
        </div>

        <div>
          <h4>Dragon Oak Studio</h4>
          <div class="footer-links">
            <p>Laser Crafted</p>
            <p>UV Printed</p>
            <p>Digital Designs</p>
            <p>Custom Creations</p>
          </div>
        </div>
      </div>

      <p class="copyright">
        © <span id="year"></span> Dragon Oak Studio. All Rights Reserved.
      </p>
    </div>
  </footer>`;

const layout = ({ title, description, canonicalPath, ogImage, ogImageAlt, noindex, jsonLd, activeNav, body }) => {
  const fullTitle = `${title} | ${SITE_NAME}`;
  const canonical = absoluteUrl(canonicalPath);
  const image = absoluteUrl(ogImage || DEFAULT_SOCIAL_IMAGE);
  const imageAlt = ogImageAlt || "Dragon Oak Studio - Crafted by Fire. Designed to Last.";
  const jsonLdTags = (jsonLd || [])
    .map((entry) => `  <script type="application/ld+json">${safeJsonLd(entry)}</script>`)
    .join("\n");

  return `<!DOCTYPE html>
<!-- ${GENERATED_NOTE} -->
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="${escapeHtml(description)}" />
  <title>${escapeHtml(fullTitle)}</title>
  <link rel="canonical" href="${escapeHtml(canonical)}" />${noindex ? '\n  <meta name="robots" content="noindex, follow" />' : ""}
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${escapeHtml(canonical)}" />
  <meta property="og:title" content="${escapeHtml(fullTitle)}" />
  <meta property="og:description" content="${escapeHtml(description)}" />
  <meta property="og:image" content="${escapeHtml(image)}" />
  <meta property="og:image:alt" content="${escapeHtml(imageAlt)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escapeHtml(fullTitle)}" />
  <meta name="twitter:description" content="${escapeHtml(description)}" />
  <meta name="twitter:image" content="${escapeHtml(image)}" />
  <link rel="icon" href="/assets/dragon-oak-logo.webp" type="image/webp" />
  <link rel="stylesheet" href="/css/styles.css" />
  <link rel="stylesheet" href="/css/storefront.css" />
  <script src="/js/main.js?v=phase-ii-intro" defer></script>
  <script src="/js/shop.js" defer></script>
${jsonLdTags}
</head>

<body>
${headerHtml({ activeNav })}

  <main class="shop-main">
${body}
  </main>

${footerHtml()}
</body>
</html>
`;
};

const breadcrumbJsonLd = (crumbs) => ({
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: crumbs.map((crumb, index) => ({
    "@type": "ListItem",
    position: index + 1,
    name: crumb.name,
    item: absoluteUrl(crumb.path),
  })),
});

const breadcrumbHtml = (crumbs) => {
  const items = crumbs
    .map((crumb, index) =>
      index === crumbs.length - 1
        ? `<li aria-current="page">${escapeHtml(crumb.name)}</li>`
        : `<li><a href="${escapeHtml(crumb.path)}">${escapeHtml(crumb.name)}</a></li>`
    )
    .join("");

  return `<nav class="breadcrumb" aria-label="Breadcrumb"><ol>${items}</ol></nav>`;
};

const typeBadge = (productType) =>
  `<span class="type-badge type-${productType === "digital_download" ? "digital" : "physical"}">${escapeHtml(
    PRODUCT_TYPE_LABELS[productType] || productType
  )}</span>`;

const productCard = (product) => {
  const image = product.images[0];

  return `<article class="shop-card" data-product-type="${escapeHtml(product.productType)}" data-subcollection="${escapeHtml(
    product.subcollection || ""
  )}">
            <a class="shop-card-link" href="${escapeHtml(product.url)}">
              <div class="shop-card-art">
                <img src="${escapeHtml(imageUrl(image.path))}" alt="${escapeHtml(image.alt)}" loading="lazy" decoding="async" />
              </div>
              <div class="shop-card-body">
                ${typeBadge(product.productType)}
                <h3>${escapeHtml(product.title)}</h3>
                <p class="shop-card-price">${product.price ? escapeHtml(product.price.display) : "Ask for details"}</p>
              </div>
            </a>
          </article>`;
};

const productGrid = (products) => `<div class="shop-grid" data-shop-grid>
          ${products.map(productCard).join("\n          ")}
        </div>`;

const collectionCard = (collection) => `<a class="collection-card" href="${escapeHtml(collection.url)}">
          <span class="collection-count">${collection.count > 0 ? pluralPieces(collection.count) : "Coming soon"}</span>
          <h3>${escapeHtml(collection.name)}</h3>
          <p>${escapeHtml(collection.tagline)}</p>
          <span class="collection-cta" aria-hidden="true">Browse →</span>
        </a>`;

const collectionGrid = (collections) => `<div class="collection-grid">
        ${collections.map(collectionCard).join("\n        ")}
      </div>`;

// ---- Pages -----------------------------------------------------------------------------------------------------

const renderShopIndex = (catalog) => {
  const featured = catalog.products.filter((product) => product.featured).slice(0, 6);
  const featuredBlock = featured.length
    ? `
      <h2 class="shop-subhead">Featured Pieces</h2>
      ${productGrid(featured)}`
    : "";

  return layout({
    title: "Shop",
    description:
      "Shop Dragon Oak Studio by collection: Halloween, Christmas, Cute Bookmarks, Wine & Hill Country, and Parties & Celebrations.",
    canonicalPath: "/shop/",
    activeNav: "shop",
    jsonLd: [breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Shop", path: "/shop/" }])],
    body: `    <section class="shop-hero">
      <div class="container">
        ${breadcrumbHtml([{ name: "Home", path: "/" }, { name: "Shop", path: "/shop/" }])}
        <p class="section-kicker">Shop</p>
        <h1 class="shop-title">Shop Dragon Oak Studio</h1>
        <p class="section-intro">
          Browse by season and theme. Each collection can be filtered by digital download or physical product.
        </p>
      </div>
    </section>

    <section class="shop-section">
      <div class="container">
      ${collectionGrid(catalog.collections)}${featuredBlock}
      </div>
    </section>`,
  });
};

const uniqueSorted = (values) => Array.from(new Set(values.filter(Boolean))).sort((a, b) => a.localeCompare(b));
const subcollectionLabel = (slug) => slug.replace(/-/g, " ").replace(/\b[a-z]/g, (letter) => letter.toUpperCase());

const filterBar = (products) => {
  const types = uniqueSorted(products.map((product) => product.productType));
  const subcollections = uniqueSorted(products.map((product) => product.subcollection));
  const groups = [];

  if (types.length > 1) {
    groups.push(`<div class="filter-group" role="group" aria-label="Filter by product type">
          <button type="button" class="filter-chip is-active" data-filter="type" data-value="" aria-pressed="true">All</button>
          ${types
            .map(
              (type) =>
                `<button type="button" class="filter-chip" data-filter="type" data-value="${escapeHtml(type)}" aria-pressed="false">${escapeHtml(
                  PRODUCT_TYPE_LABELS[type]
                )}</button>`
            )
            .join("\n          ")}
        </div>`);
  }

  if (subcollections.length > 1) {
    groups.push(`<div class="filter-group" role="group" aria-label="Filter by type of piece">
          <button type="button" class="filter-chip is-active" data-filter="sub" data-value="" aria-pressed="true">All pieces</button>
          ${subcollections
            .map(
              (slug) =>
                `<button type="button" class="filter-chip" data-filter="sub" data-value="${escapeHtml(slug)}" aria-pressed="false">${escapeHtml(
                  subcollectionLabel(slug)
                )}</button>`
            )
            .join("\n          ")}
        </div>`);
  }

  if (!groups.length) {
    return "";
  }

  return `<div class="filter-bar" data-filter-bar>
        ${groups.join("\n        ")}
        <p class="filter-status" data-filter-status role="status" aria-live="polite"></p>
      </div>
      <p class="filter-empty" data-filter-empty hidden>No pieces match those filters. Try choosing "All".</p>`;
};

const renderCollectionPage = (collection, catalog) => {
  const products = catalog.products.filter((product) => product.collection === collection.slug);
  const crumbs = [
    { name: "Home", path: "/" },
    { name: "Shop", path: "/shop/" },
    { name: collection.name, path: collection.url },
  ];
  const other = catalog.collections.filter((entry) => entry.slug !== collection.slug);
  const filters = products.length ? filterBar(products) : "";
  const content = products.length
    ? `${filters ? `${filters}\n      ` : ""}${productGrid(products)}`
    : `<div class="shop-empty">
        <h2>New pieces are on the way</h2>
        <p>We're preparing the ${escapeHtml(collection.name)} collection. Browse another collection, or tell us what you have in mind.</p>
        <div class="shop-empty-actions">
          <a class="btn btn-primary" href="/#contact">Ask About Custom Work</a>
          <a class="btn btn-outline" href="/shop/">Browse All Collections</a>
        </div>
      </div>`;

  return layout({
    title: collection.name,
    description: collection.description,
    canonicalPath: collection.url,
    noindex: products.length === 0,
    activeNav: "shop",
    ogImage: products.length ? imageUrl(products[0].images[0].path) : undefined,
    ogImageAlt: products.length ? products[0].images[0].alt : undefined,
    jsonLd: [breadcrumbJsonLd(crumbs)],
    body: `    <section class="shop-hero">
      <div class="container">
        ${breadcrumbHtml(crumbs)}
        <p class="section-kicker">Collection</p>
        <h1 class="shop-title">${escapeHtml(collection.name)}</h1>
        <p class="section-intro">${escapeHtml(collection.tagline)} ${escapeHtml(collection.description)}</p>
      </div>
    </section>

    <section class="shop-section">
      <div class="container">
      ${content}
      <h2 class="shop-subhead">More Collections</h2>
      ${collectionGrid(other)}
      </div>
    </section>`,
  });
};

const productMetaRow = (label, value) => `<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`;

const renderProductPage = (product, collection, catalog) => {
  const related = catalog.products
    .filter((entry) => entry.collection === product.collection && entry.id !== product.id)
    .slice(0, 4);
  const crumbs = [
    { name: "Home", path: "/" },
    { name: "Shop", path: "/shop/" },
    { name: collection.name, path: collection.url },
    { name: product.title, path: product.url },
  ];
  const firstImage = product.images[0];
  const gallery = product.images
    .map(
      (image, index) => `<figure class="product-figure${index === 0 ? " is-primary" : ""}">
              <img src="${escapeHtml(imageUrl(image.path))}" alt="${escapeHtml(image.alt)}"${index === 0 ? "" : ' loading="lazy"'} decoding="async" />
            </figure>`
    )
    .join("\n            ");
  const actions = product.buyUrl
    ? `<a class="btn btn-primary" href="${escapeHtml(product.buyUrl)}" target="_blank" rel="noopener noreferrer">Buy on Etsy</a>
            <p class="product-note">You'll complete your purchase on Etsy.</p>`
    : `<a class="btn btn-primary" href="/#contact">Ask About This Piece</a>
            <p class="product-note">This piece isn't listed for online purchase right now. Send us a message and we'll help.</p>`;
  const meta = [
    productMetaRow("Collection", collection.name),
    productMetaRow("Type", PRODUCT_TYPE_LABELS[product.productType]),
    product.subcollection ? productMetaRow("Category", subcollectionLabel(product.subcollection)) : "",
    productMetaRow("SKU", product.sku),
  ].join("");
  const tags = product.tags.length
    ? `<ul class="tag-list" aria-label="Tags">${product.tags.map((tag) => `<li>${escapeHtml(tag)}</li>`).join("")}</ul>`
    : "";
  const productJsonLd = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: product.title,
    description: product.description,
    sku: product.sku,
    url: absoluteUrl(product.url),
    image: product.images.map((image) => absoluteUrl(imageUrl(image.path))),
    brand: { "@type": "Brand", name: SITE_NAME },
  };

  if (product.price && product.buyUrl) {
    productJsonLd.offers = {
      "@type": "Offer",
      price: (product.price.amountCents / 100).toFixed(2),
      priceCurrency: product.price.currency,
      availability: "https://schema.org/InStock",
      url: product.buyUrl,
    };
  }

  const relatedBlock = related.length
    ? `
      <h2 class="shop-subhead">More from ${escapeHtml(collection.name)}</h2>
      ${productGrid(related)}`
    : "";

  return layout({
    title: product.title,
    description: product.description.replace(/\s+/g, " ").trim().slice(0, 200),
    canonicalPath: product.url,
    ogImage: imageUrl(firstImage.path),
    ogImageAlt: firstImage.alt,
    activeNav: "shop",
    jsonLd: [productJsonLd, breadcrumbJsonLd(crumbs)],
    body: `    <section class="shop-section product-section">
      <div class="container">
        ${breadcrumbHtml(crumbs)}
        <div class="product-detail">
          <div class="product-gallery">
            ${gallery}
          </div>

          <div class="product-info">
            <p class="section-kicker">${escapeHtml(collection.name)}</p>
            <h1 class="shop-title product-title">${escapeHtml(product.title)}</h1>
            <p class="product-badges">${typeBadge(product.productType)}</p>
            <p class="product-price">${product.price ? escapeHtml(product.price.display) : "Ask for details"}</p>
            ${paragraphs(product.description)}
            <dl class="product-meta">${meta}</dl>
            ${tags}
            <div class="product-actions">
            ${actions}
            <a class="btn btn-outline" href="${escapeHtml(collection.url)}">Back to ${escapeHtml(collection.name)}</a>
            </div>
          </div>
        </div>${relatedBlock}
      </div>
    </section>`,
  });
};

// The generated "Shop by Collection" section that lives between the markers in index.html.
const renderHomeCollectionsSection = (catalog) => {
  const featured = catalog.products.filter((product) => product.featured).slice(0, 6);
  const featuredBlock = featured.length
    ? `
      <h3 class="shop-subhead">Featured Pieces</h3>
      ${productGrid(featured)}`
    : "";

  return `${HOME_MARKERS.start}
    <section class="collections-section" id="collections">
      <div class="container">
        <p class="section-kicker">Shop</p>
        <h2 class="section-title">Shop by Collection</h2>

        <p class="section-intro">
          Browse Dragon Oak Studio by season and theme, then filter by digital
          download or physical product.
        </p>

        ${collectionGrid(catalog.collections)}${featuredBlock}

        <p class="collections-all"><a class="btn btn-outline" href="/shop/">View the Full Shop</a></p>
      </div>
    </section>
    ${HOME_MARKERS.end}`;
};

const replaceHomeSection = (html, sectionHtml) => {
  const startIndex = html.indexOf("<!-- storefront:collections:start");
  const endIndex = html.indexOf(HOME_MARKERS.end);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error("index.html is missing the storefront:collections start/end markers.");
  }

  return `${html.slice(0, startIndex)}${sectionHtml}${html.slice(endIndex + HOME_MARKERS.end.length)}`;
};

const renderSitemap = (catalog) => {
  const entry = (loc, lastmod) =>
    `  <url>\n    <loc>${escapeHtml(loc)}</loc>${lastmod ? `\n    <lastmod>${escapeHtml(lastmod)}</lastmod>` : ""}\n  </url>`;
  const entries = [entry(`${SITE_ORIGIN}/`), entry(`${SITE_ORIGIN}/shop/`)];

  catalog.collections
    .filter((collection) => collection.count > 0)
    .forEach((collection) => entries.push(entry(absoluteUrl(collection.url))));

  catalog.products.forEach((product) =>
    entries.push(entry(absoluteUrl(product.url), product.updatedAt.slice(0, 10)))
  );

  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join("\n")}\n</urlset>\n`;
};

module.exports = {
  HOME_MARKERS,
  escapeHtml,
  renderCollectionPage,
  renderHomeCollectionsSection,
  renderProductPage,
  renderShopIndex,
  renderSitemap,
  replaceHomeSection,
  safeJsonLd,
};
